
version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: paywell
    env_file:
      - ./.env
    ports:
      - '3307:3306'
    volumes:
      - mysqlDb:/var/lib/mysql
volumes:
  mysqlDb: